# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: bash -c 'ruff format .'
        language: system
  - repo: local
    hooks:
    - id: ruff-check
      name: ruff-check
      entry: bash -c 'ruff check .'
      language: system
  - repo: local
    hooks:
      - id: pytest
        name: pytest-check
        entry: bash -c 'pytest'
        language: system
