# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: black
        name: black-formatter
        entry: bash -c 'black .'
        language: system
  - repo: local
    hooks:
    - id: flake8
      name: flake8-linter
      entry: bash -c 'flake8 .'
      language: system
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: bash -c 'pytest'
        language: system
